### ISSUE TITLE
Using pre-commit hooks for all via rusty-hook ?

### ISSUE THREAD

**Issue by matclab** [secretkeysio/jelly-actix-web-starter#20]
Would you mind if we start using the dev dependency [rusty-hook](https://github.com/swellaby/rusty-hook). Configured with the following  `.rusty-hook.toml` 
```toml           
[hooks]
pre-commit = "cargo check && cargo fmt -- --check" #&& cargo test"
pre-push = "cargo check && cargo fmt -- --check"

[logging]
verbose = true
```

It would allow every developer on this project to benefit of git hooks to ensure that every commit is formatted and checked. Once we have more unit and integrations test in place we could also enable `cargo test` in `pre-push` or `pre-commit`.

Not so important,  but I'm using it and guess it may be of interest to others.
